# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hired',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
